aspnet/Logging

src/Microsoft.Framework.Logging.Interfaces/ILogger.cs
src/Microsoft.Framework.Logging/DiagnosticsLoggerProvider.cs

Addresses bug https://github.com/aspnet/Logging/issues/18
@Tratcher

Removing 'OWIN' from XML comments

---

src/Microsoft.Framework.Logging.Interfaces/LogLevel.cs
test/Microsoft.Framework.Logging.Test/LogLevelEnumTest.cs

Just changing the enum to address #103

Adding debug level to logLevel enum

---

src/Microsoft.Framework.Logging/LoggerExtensions.cs
test/Microsoft.Framework.Logging.Test/LoggerExtensionsTest.cs

This should bring the extension support for the debug level on par with the other levels

Adding extension methods for logging at debug level

---

test/Microsoft.Framework.Logging.Test/BeginScopeContext.cs
test/Microsoft.Framework.Logging.Test/TestLogger.cs
test/Microsoft.Framework.Logging.Test/TestLoggerFactory.cs
test/Microsoft.Framework.Logging.Test/TestSink.cs

Moving testing classes to testing namespace and testing folder

---

src/Microsoft.Framework.Logging.Console/IConsole.cs
src/Microsoft.Framework.Logging.Console/LogConsole.cs
test/Microsoft.Framework.Logging.Test/Console/TestConsole.cs
test/Microsoft.Framework.Logging.Test/ConsoleLoggerTest.cs

Whoops!
/cc @Praburaj @BrennanConroy

ensure curly braces in log messages works after I broke it :)

---

build.cmd
build.sh
samples/SampleApp/Program.cs
samples/SampleApp/project.json
src/Microsoft.Framework.Logging.Console/project.json
src/Microsoft.Framework.Logging.Interfaces/project.json
src/Microsoft.Framework.Logging.NLog/project.json
src/Microsoft.Framework.Logging.Serilog/SerilogLoggerProvider.cs
src/Microsoft.Framework.Logging.Serilog/SerilogLoggerScope.cs
src/Microsoft.Framework.Logging.Serilog/project.json
src/Microsoft.Framework.Logging.TraceSource/Internal/TraceSourceScope.cs
src/Microsoft.Framework.Logging.TraceSource/project.json
src/Microsoft.Framework.Logging/project.json
test/Microsoft.Framework.Logging.Test/LoggerFactoryExtensionsTest.cs
test/Microsoft.Framework.Logging.Test/TraceSourceScopeTest.cs
test/Microsoft.Framework.Logging.Test/project.json

Prepping to be merged once ready.

Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

---

src/Microsoft.Framework.Logging/Logger.cs

* Logger.Log shouldn't call IsEnabled on individual loggers, at that
point it's just unnecessary overhead
* Logger.IsEnabled shouldn't use .Any for performance reasons

Fixing some Logger implementation details

---

README.md

This is a re-PR because the original PR (#163) failed to update with my commits.
- NuGet badges.
- AppVeyor badge.
- Travis badge.
NOTE! Badges reference the dev branches.
Reference: #161

:sparkling_heart: Added badges! (Take 2)

---

test/Microsoft.Framework.Logging.Test/FormattedLogValuesTest.cs
test/Microsoft.Framework.Logging.Test/project.json

Removed dependency on HttpExtensions package

---

src/Microsoft.Framework.Logging.Abstractions/project.json
src/Microsoft.Framework.Logging.Console/project.json
src/Microsoft.Framework.Logging.TraceSource/Internal/TraceSourceScope.cs
src/Microsoft.Framework.Logging.TraceSource/project.json
src/Microsoft.Framework.Logging/project.json

Depends on aspnet/DependencyInjection#245

dotnet all the things

---

src/Microsoft.Framework.Logging.Console/ConsoleLogger.cs
src/Microsoft.Framework.Logging.Console/Internal/IConsole.cs
src/Microsoft.Framework.Logging.Console/LogConsole.cs
test/Microsoft.Framework.Logging.Test/Console/TestConsole.cs

@davidfowl @muratg @Eilon 
#202

Reset color in a cross-plat friendly way

---

src/Microsoft.Framework.Logging.Debug/DebugLogger.cs
src/Microsoft.Framework.Logging.Debug/DebugLogger.debug.cs

Fixes https://github.com/aspnet/Logging/issues/216
@kichalla @Eilon

Define the DEBUG symbol on Release

---

README.md

This time without change of line endings :)

Added the elmah.io provider to the list of community projects

---

Logging.sln
samples/SampleApp/Program.cs
samples/SampleApp/project.json
src/Microsoft.Framework.Logging.Console/ConsoleLogger.cs
src/Microsoft.Framework.Logging.Debug/DebugLogger.cs
src/Microsoft.Framework.Logging.EventLog/EventLogLogger.cs
src/Microsoft.Framework.Logging.EventLog/EventLogLoggerProvider.cs
src/Microsoft.Framework.Logging.EventLog/EventLogSettings.cs
src/Microsoft.Framework.Logging.EventLog/EventLoggerFactoryExtensions.cs
src/Microsoft.Framework.Logging.EventLog/Microsoft.Framework.Logging.EventLog.xproj
src/Microsoft.Framework.Logging.EventLog/project.json
test/Microsoft.Framework.Logging.Test/ConsoleLoggerTest.cs
test/Microsoft.Framework.Logging.Test/DebugLoggerTest.cs
test/Microsoft.Framework.Logging.Test/EventLogLoggerTest.cs
test/Microsoft.Framework.Logging.Test/project.json

@Eilon
- This PR does not reflect all the details of the PR : https://github.com/aspnet/Logging/pull/147/ as it has details like HttpContext(which is incorrect as the logger can be used outside the context of aspnet) and creation of event source(which requires admin privileges and is not really a job of this logger).

Logger for Windows Event Log

---

src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
src/Microsoft.Extensions.Logging.Console/Internal/IConsole.cs
src/Microsoft.Extensions.Logging.Console/LogConsole.cs
test/Microsoft.Extensions.Logging.Test/Console/TestConsole.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

Fix console logging formatting

---

samples/SampleApp/Program.cs
src/Microsoft.Extensions.Logging.Console/ConsoleLogScope.cs
src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
src/Microsoft.Extensions.Logging.Console/ConsoleLoggerFactoryExtensions.cs
src/Microsoft.Extensions.Logging.Console/ConsoleLoggerProvider.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

Added scoping information to Console logger

---

samples/SampleApp/logging.json
src/Microsoft.Extensions.Logging.Console/ConfigurationConsoleLoggerSettings.cs

Rename 'switches' to 'LogLevel'

---

src/Microsoft.Extensions.Logging.TraceSource/TraceSourceScope.cs

Clean up duplicated #if's for NET451

---

src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
src/Microsoft.Extensions.Logging.Console/project.json

- Use RuntimeInformation to detect the OS
#309

Avoid DNXisms when unneeded

---

src/Microsoft.Extensions.Logging.Testing/TestLogger.cs

@BrennanConroy @kichalla This should fix the build.

Fix build by creating non-null scope during BeginScopeImpl

---

.gitignore
.travis.yml
appveyor.yml
build.cmd
build.sh
test/Microsoft.Extensions.Logging.Test/project.json
test/Microsoft.Extensions.Logging.Testing.Tests/project.json

Build with dotnet

---

samples/SampleApp/Program.cs
samples/SampleApp/project.json

React to FileProviders namespace changes

---

README.md

We've created a library for Loggr, so add it to the list.

Add Loggr extensions library reference

---

src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs
src/Microsoft.Extensions.Logging.Abstractions/Internal/LogValuesFormatter.cs
test/Microsoft.Extensions.Logging.Test/FormattedLogValuesTest.cs

Fix case where no args passed to Log* extensions

---

samples/SampleApp/project.json
src/Microsoft.Extensions.Logging.Abstractions/project.json
src/Microsoft.Extensions.Logging.Console/project.json
src/Microsoft.Extensions.Logging.Debug/project.json
src/Microsoft.Extensions.Logging.TraceSource/project.json
src/Microsoft.Extensions.Logging/project.json
test/Microsoft.Extensions.Logging.Test/project.json
test/Microsoft.Extensions.Logging.Testing.Tests/project.json

Remove netcore50

---

src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

Print exception not just message

---

README.md

Added NLog provider

---

README.md

Update link for rename NLog.Framework.logging => NLog.Extensions.Logging

---

NuGetPackageVerifier.json
src/Microsoft.Extensions.Logging.Abstractions/ILoggerOfT.cs
src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs
src/Microsoft.Extensions.Logging.Abstractions/Internal/LogValuesFormatter.cs
src/Microsoft.Extensions.Logging.Abstractions/LoggerMessage.cs
src/Microsoft.Extensions.Logging.Abstractions/project.json
src/Microsoft.Extensions.Logging.Console/ConsoleLoggerFactoryExtensions.cs
src/Microsoft.Extensions.Logging.Console/project.json
src/Microsoft.Extensions.Logging.Debug/project.json
src/Microsoft.Extensions.Logging.EventLog/project.json
src/Microsoft.Extensions.Logging.Testing/LogValuesAssert.cs
src/Microsoft.Extensions.Logging.Testing/project.json
src/Microsoft.Extensions.Logging.TraceSource/TraceSourceScope.cs
src/Microsoft.Extensions.Logging.TraceSource/project.json
src/Microsoft.Extensions.Logging/project.json

Enabled xml doc generation

---

src/Microsoft.Extensions.Logging.TraceSource/TraceSourceLogger.cs
src/Microsoft.Extensions.Logging.TraceSource/TraceSourceScope.cs

Make TraceSourceLogger public

---

src/Microsoft.Extensions.Logging.EventLog/EventLogLogger.cs

Add Exception to EventLogger output

---

README.md
src/Microsoft.Extensions.Logging.Abstractions/project.json
src/Microsoft.Extensions.Logging.Console/project.json
src/Microsoft.Extensions.Logging.Debug/DebugLogger.cs
src/Microsoft.Extensions.Logging.Debug/project.json
src/Microsoft.Extensions.Logging.EventLog/project.json
src/Microsoft.Extensions.Logging.Testing/project.json
src/Microsoft.Extensions.Logging.TraceSource/project.json
src/Microsoft.Extensions.Logging/project.json

@lodejard @BrennanConroy @kichalla

Fix package metadata

---

src/Microsoft.Extensions.Logging.Console/project.json

This reverts commit b4b112981afece16e3008df0efc6e6de24ea9184.

Revert "Reacting to CoreCLR package changes"

---

src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
src/Microsoft.Extensions.Logging.Debug/DebugLogger.debug.cs
src/Microsoft.Extensions.Logging.Debug/project.json
test/Microsoft.Extensions.Logging.Test/DebugLoggerTest.cs

https://github.com/aspnet/DataProtection/issues/129
@pranavkm @muratg @Eilon

Fix overload of Debug.WriteLine we are using

---

test/Microsoft.Extensions.Logging.Test/EventLogLoggerTest.cs
test/Microsoft.Extensions.Logging.Test/TraceSourceLoggerProviderTest.cs
test/Microsoft.Extensions.Logging.Test/TraceSourceLoggerTest.cs
test/Microsoft.Extensions.Logging.Test/TraceSourceScopeTest.cs

Add missing tests from DNX451 -> NET451 rename

---

.gitattributes
src/Microsoft.Extensions.Logging.Abstractions/project.json
src/Microsoft.Extensions.Logging/project.json

Part of https://github.com/aspnet/EntityFramework/pull/5021

Cross-compile to netcore50 to support EF on UWP

---

samples/SampleApp/Program.cs
samples/SampleApp/project.json
test/Microsoft.Extensions.Logging.Test/project.json
test/Microsoft.Extensions.Logging.Testing.Tests/project.json

Migrate tests/samples/tools to portable

---

src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

#406 
@lodejard @kichalla @muratg

Color only log level

---

src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
src/Microsoft.Extensions.Logging.Console/Internal/AnsiLogConsole.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

#417 
@davidfowl @kichalla @muratg

Fix unix Console colors

---

src/Microsoft.Extensions.Logging.Filter/Microsoft.Extensions.Logging.Filter.xproj

Fix .xproj to build in VS

---

src/Microsoft.Extensions.Logging.Testing/ITestSink.cs
src/Microsoft.Extensions.Logging.Testing/TestLogger.cs
src/Microsoft.Extensions.Logging.Testing/TestLoggerFactory.cs
src/Microsoft.Extensions.Logging.Testing/TestSink.cs

I want to write a different test sink and right now there's no simple way to it. Introducing this interfaces allows for different test sinks to be implement according to testing needs.
cc @kichalla @BrennanConroy @pranavkm

Add ITestSink interface.

---

src/Microsoft.Extensions.Logging.Console/ConsoleLogScope.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

@Tratcher @davidfowl @kichalla 
Related to https://github.com/aspnet/Caching/issues/203

AppDomain safety

---

src/Microsoft.Extensions.Logging.Abstractions/NullLogger.cs
src/Microsoft.Extensions.Logging.Abstractions/NullLoggerProvider.cs
src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/AzureWebAppDiagnosticsLoggerProvider.cs

#473 
Should NullScope also be moved?

Move NullLogger out of Internal

---

src/Microsoft.Extensions.Logging/LoggerFactory.cs
test/Microsoft.Extensions.Logging.Test/LoggerFactoryTest.cs

Resolve #418 
cc @muratg @BrennanConroy

LoggerFactory public methods throw ObjectDisposedException after dispose

---

test/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.Test/LogConfigurationReaderTests.cs
test/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.Test/RetryHelper.cs

Fixes https://github.com/aspnet/Logging/issues/474
Please review @BrennanConroy

Make the ConfigurationChange test stable

---

test/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.Test/AzureBlobSinkTests.cs

Fix blob sink tests

---

src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

@davidfowl @glennc @halter73 @rynowak 
~35% increase with an app hosted in azure.
Ignore test failures for now.

Faster Console Logger Mark 1

---

test/Microsoft.Extensions.Logging.Azure.AppServicesDiagnostics.Test/AzureBlobSinkTests.cs
test/Microsoft.Extensions.Logging.Azure.AppServicesDiagnostics.Test/BackgroundSinkTests.cs
test/Microsoft.Extensions.Logging.Azure.AppServicesDiagnostics.Test/LogConfigurationReaderTests.cs
test/Microsoft.Extensions.Logging.Azure.AppServicesDiagnostics.Test/SerilogLoggerProviderTests.cs
test/Microsoft.Extensions.Logging.Azure.AppServicesDiagnostics.Test/project.json

Fix Microsoft.Extensions.Logging.Azure.AppServicesDiagnostics.Test test project

---

src/Microsoft.Extensions.Logging.AzureAppServices/Internal/WebAppLogConfiguration.cs
src/Microsoft.Extensions.Logging.AzureAppServices/Internal/WebConfigurationReaderLevelSwitch.cs
test/Microsoft.Extensions.Logging.AzureAppServices.Test/WebConfigurationLevelSwitchTests.cs

Fixes: https://github.com/aspnet/Logging/issues/517
Fixes: https://github.com/aspnet/AzureIntegration/issues/5

Read initial level values on application start

---

src/Microsoft.Extensions.Logging.AzureAppServices/Internal/WebAppLogConfiguration.cs
src/Microsoft.Extensions.Logging.AzureAppServices/Internal/WebConfigurationReaderLevelSwitch.cs
test/Microsoft.Extensions.Logging.AzureAppServices.Test/WebConfigurationLevelSwitchTests.cs

See https://github.com/aspnet/Logging/issues/544

Port "Read initial level values on application start (#544)" to 1.1.1

---

src/Microsoft.Extensions.Logging.AzureAppServices/Microsoft.Extensions.Logging.AzureAppServices.csproj

To get scopes capture by default

Update Serilog.Extensions.Logging version

---

src/Microsoft.Extensions.Logging.Console/ConsoleLoggerProvider.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

Ensure change token is reset

---

build/dependencies.props
src/Microsoft.Extensions.Logging.AzureAppServices/Microsoft.Extensions.Logging.AzureAppServices.csproj
src/Microsoft.Extensions.Logging.Testing/Microsoft.Extensions.Logging.Testing.csproj
test/Microsoft.Extensions.Logging.AzureAppServices.Test/Microsoft.Extensions.Logging.AzureAppServices.Test.csproj

Upgrades:
Serilog.Sinks.RollingFile
Serilog.Sinks.PeriodicBatching
WindowsAzure.Storage
Removes requirement for PackageTargetFallback.

Upgrade dependencies to latest stable releases

---

src/Microsoft.Extensions.Logging.AzureAppServices/Microsoft.Extensions.Logging.AzureAppServices.csproj

Remove unneeded dependency

---

src/Microsoft.Extensions.Logging.Testing/XunitLoggerProvider.cs
test/Microsoft.Extensions.Logging.Testing.Tests/XunitLoggerProviderTest.cs

fixes #591 
blocking aspnet/Hosting#999

Xunit logger ignores exceptions from output helper

---

samples/SampleApp/Program.cs
src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
test/Microsoft.Extensions.Logging.AzureAppServices.Test/BatchingLoggerProviderTests.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

Fixes https://github.com/aspnet/Logging/issues/619

Log message header in console logger when message is empty

---

src/Microsoft.Extensions.Logging.AzureAppServices/baseline.netcore.json
src/Microsoft.Extensions.Logging.EventSource/baseline.net45.json
src/Microsoft.Extensions.Logging.EventSource/baseline.netcore.json

Generated from 1.1.0
Approved by @Eilon

Add baselines for AzureAppServicesDiagnostics and EventSource

---

src/Microsoft.Extensions.Logging.AzureAppServices/AzureAppServicesLoggerFactoryExtensions.cs
src/Microsoft.Extensions.Logging/StaticFilterOptionsMonitor.cs
test/Microsoft.Extensions.Logging.AzureAppServices.Test/OptionsWrapperMonitor.cs

React to Options

---

src/Microsoft.Extensions.Logging.Console/ConsoleLoggerProvider.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

https://github.com/aspnet/Logging/issues/665

Respect ConsoleLoggerOptions.IncludeScopes

---

src/Microsoft.Extensions.Logging.Testing/AssemblyTestLog.cs
src/Microsoft.Extensions.Logging.Testing/LoggedTest.cs

MusicStore and SignalR would need to be updated

Add minimum LogLevel to AssemblyTestLog

---

build/dependencies.props
test/Microsoft.Extensions.Logging.AzureAppServices.Test/AzureBlobSinkTests.cs
test/Microsoft.Extensions.Logging.AzureAppServices.Test/BatchingLoggerProviderTests.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs
test/Microsoft.Extensions.Logging.Test/EventLogLoggerTest.cs
test/Microsoft.Extensions.Logging.Test/LoggerExtensionsTest.cs
test/Microsoft.Extensions.Logging.Test/LoggerFilterTest.cs
test/Microsoft.Extensions.Logging.Test/LoggerMessageTest.cs
test/Microsoft.Extensions.Logging.Test/LoggerTest.cs

Required a few changes due to xunit.analyzers. In particular, I changed one test that had an unused theory parameter.

Upgrade to xunit 2.3.0-beta4

---

src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs
test/Microsoft.Extensions.Logging.Test/LoggerExtensionsTest.cs

Added generic Log method to extension. 

---

src/Microsoft.Extensions.Logging.Configuration/LoggerProviderConfigurationFactory.cs
test/Microsoft.Extensions.Logging.Test/LoggerProviderConfigurationFactoryTest.cs

https://github.com/aspnet/Logging/issues/722

Fix logger provider configuration reload after adding section

---

src/Microsoft.Extensions.Logging.Testing/XunitLoggerProvider.cs

I was seeing sheared xunit log messages when using the logs from a multi-threaded test. The lines are written atomically, but we write multi-line messages with separate `WriteLine` calls so we need to buffer them to avoid shearing.

fix sheared xunit log messages by buffering the message

---

src/Microsoft.Extensions.Logging.Configuration/baseline.netcore.json
src/Microsoft.Extensions.Logging.Testing/baseline.netcore.json

These packages were missing baselines, so I added them.

Add missing baselines

---

src/Microsoft.Extensions.Logging.Console/Internal/ConsoleLoggerProcessor.cs

Using `Task.Factory.StartNew`, without specifying a task scheduler or
denying child attach or any of a half dozen non-obvious flags/parameters
can cause undesired behavior from the task. This hidden behavior causes
any uses of the console logger in Xamarin Workbooks to hijack the main thread,
preventing further execution, regardless of the workbook platform (.NET Core,
iOS, Desktop .NET all exhibit this issue at slightly different points).
See this article for some of the dangers of `Task.Factory.StartNew`,
particularly around not using `DenyChildAttach`, and why `LongRunning`
is unnecessary: https://blog.stephencleary.com/2013/08/startnew-is-dangerous.html.
This PR replaces `Task.Factory.StartNew` with `Task.Run`, which is semantically more
correct, functionally equivalent, and more …

Don't use Task.Factory.StartNew, it's dangerous

---

src/Microsoft.Extensions.Logging.Abstractions/EventId.cs
test/Microsoft.Extensions.Logging.Test/EventIdTest.cs

Fix #607 - Implements equality members on EventId.

---

build/dependencies.props
src/Microsoft.Extensions.Logging.EventLog/Microsoft.Extensions.Logging.EventLog.csproj
test/Microsoft.Extensions.Logging.Test/EventLogLoggerTest.cs
test/Microsoft.Extensions.Logging.Test/Microsoft.Extensions.Logging.Test.csproj

Cross compile library and tests.
Fixes https://github.com/aspnet/Logging/issues/751

Add EventLog support for netstandard20

---

src/Microsoft.Extensions.Logging.Testing/XunitLoggerProvider.cs
test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs
test/Microsoft.Extensions.Logging.Testing.Tests/XunitLoggerProviderTest.cs

Debugging some tests and timestamps would be very useful.

add timestamp to test logs

---

src/Microsoft.Extensions.Logging.Testing/AssemblyTestLog.cs
test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs

Some ideas for improvements while working on https://github.com/aspnet/KestrelHttpServer/pull/2433

 Add long path and collision handling to test logger

---

src/Microsoft.Extensions.Logging.Testing/AssemblyTestLog.cs
src/Microsoft.Extensions.Logging.Testing/LoggedTest.cs
src/Microsoft.Extensions.Logging.Testing/ShortClassNameAttribute.cs
src/Microsoft.Extensions.Logging.Testing/Xunit/LoggedTestInvoker.cs
src/Microsoft.Extensions.Logging.Testing/build/Microsoft.Extensions.Logging.Testing.props
test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs
test/Microsoft.Extensions.Logging.Testing.Tests/LoggedTestXunitTests.cs

Let me know if I missed any other feedback items.
This also adds an attribute to specify using the short name for the class for the assembly test log.

More feedback items and improvements for test logging

---

src/Microsoft.Extensions.Logging.Testing/WriteContext.cs

Working on https://github.com/aspnet/KestrelHttpServer/pull/2479 and noticed this would help.

Add Message on WriteContext for formatted string

---

src/Microsoft.Extensions.Logging.Testing/LoggedTest.cs
src/Microsoft.Extensions.Logging.Testing/Xunit/LoggedTestInvoker.cs
test/Microsoft.Extensions.Logging.Testing.Tests/LoggedTestXunitTests.cs

Addtional setup step for LoggedTest

---

src/Microsoft.Extensions.Logging.Testing/ITestSink.cs
src/Microsoft.Extensions.Logging.Testing/TestSink.cs
test/Microsoft.Extensions.Logging.Test/LoggerExtensionsTest.cs
test/Microsoft.Extensions.Logging.Test/LoggerFactoryExtensionsTest.cs

Found some concurrency issues while adding logging to Kestrel

Fix concurrency issue

---

build/dependencies.props
src/Microsoft.Extensions.Logging.Testing/AssemblyTestLog.cs
test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs

See https://github.com/serilog/serilog/issues/956

Don't double quote AssemblyTestLog parameters

---

test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs

https://github.com/aspnet/AspNetCore/issues/3696

Shorten test log name in test

---

src/Microsoft.Extensions.Logging.Testing/ITestSink.cs
src/Microsoft.Extensions.Logging.Testing/TestSink.cs
test/Microsoft.Extensions.Logging.Testing.Tests/LoggedTestXunitTests.cs

Fixes: https://github.com/aspnet/Logging/issues/841

Add ScopeStarted and MessageLogged event to TestSink

---

samples/SampleApp/SampleApp.csproj
samples/SampleApp/logging.json
src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
src/Microsoft.Extensions.Logging.Console/ConsoleLoggerOptions.cs
src/Microsoft.Extensions.Logging.Console/ConsoleLoggerProvider.cs
src/Microsoft.Extensions.Logging.Console/Internal/ConsoleLoggerProcessor.cs
src/Microsoft.Extensions.Logging.Console/Internal/LogMessageEntry.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

Fixes: https://github.com/aspnet/Logging/issues/483

Add timestamp format option to console logger

---

src/Microsoft.Extensions.Logging.Console/ConsoleLoggerProvider.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

Respect ConsoleLoggerSettings.DisableColors.

---

src/Microsoft.Extensions.Logging.EventSource/LoggingEventSource.cs
src/Microsoft.Extensions.Logging.EventSource/Properties/AssemblyInfo.cs

Fixing [#899](https://github.com/aspnet/Logging/issues/899)

Making LoggingEventSource public sealed

---

samples/SampleApp/logging.json
src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
src/Microsoft.Extensions.Logging.Console/ConsoleLoggerOptions.cs
src/Microsoft.Extensions.Logging.Console/ConsoleLoggerProvider.cs
src/Microsoft.Extensions.Logging.Console/Internal/ConsoleLoggerProcessor.cs
src/Microsoft.Extensions.Logging.Console/Internal/LogMessageEntry.cs
src/Microsoft.Extensions.Logging.Console/Internal/WindowsLogConsole.cs
test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs

Fixes: https://github.com/aspnet/Logging/issues/661

Support stderr in console logger

---

src/Microsoft.Extensions.Logging.AzureAppServices/AzureAppServicesLoggerFactoryExtensions.cs
src/Microsoft.Extensions.Logging.AzureAppServices/Internal/BatchingLogger.cs
src/Microsoft.Extensions.Logging.AzureAppServices/Internal/BatchingLoggerOptions.cs
src/Microsoft.Extensions.Logging.AzureAppServices/Internal/BatchingLoggerProvider.cs
src/Microsoft.Extensions.Logging.Configuration/LoggerProviderConfigurationExtensions.cs
src/Microsoft.Extensions.Logging.Configuration/LoggerProviderConfigureOptions.cs
src/Microsoft.Extensions.Logging.Console/ConsoleLoggerFactoryExtensions.cs
test/Microsoft.Extensions.Logging.AzureAppServices.Test/BatchingLoggerProviderTests.cs

Fixes: https://github.com/aspnet/Logging/issues/818

Add scopes to azure loggers

---

src/Microsoft.Extensions.Logging.Testing/LoggedTest/LoggedTestBase.cs
src/Microsoft.Extensions.Logging.Testing/Xunit/LogLevelAttribute.cs
test/Microsoft.Extensions.Logging.Testing.Tests/LoggedTestXunitTests.cs
test/Microsoft.Extensions.Logging.Testing.Tests/Properties/AssemlyInfo.cs

Addresses: https://github.com/aspnet/Logging/issues/934.

Make LogLevelAttribute applicable to classes and assemblies
