- samples/SampleApp/Program.cs
- samples/SampleApp/project.json
- src/Microsoft.Framework.Logging.Console/ConsoleLogger.cs
- src/Microsoft.Framework.Logging.Serilog/SerilogLogger.cs
- src/Microsoft.Framework.Logging/LoggerExtensions.cs
- src/Microsoft.Framework.Logging/LoggerStructureFormat.cs
- src/Microsoft.Framework.Logging/LoggerStructureFormatter.cs
- src/Microsoft.Framework.Logging/project.json
- test/Microsoft.Framework.Logging.Test/LoggerExtensionsTest.cs
- test/Microsoft.Framework.Logging.Test/LoggerStructureFormatTest.cs
This adds ability to specify named placeholders while writing logs. 
For example: 
`logger.WriteInformation("Tests started at '{StartTime}'", DateTime.Now)` (instead of `'{0}'` => `'{StartTime}'`). 
@lodejard
> Feature structuredformatstring

- src/Microsoft.Framework.Logging.Interfaces/Internal/LogValuesFormatter.cs
- test/Microsoft.Framework.Logging.Test/FormattedLogValuesTest.cs
- test/Microsoft.Framework.Logging.Test/project.json
@rynowak @lodejard @Eilon 
Text loggers like Console use the `Format` method to get the string representation of the log values. The current logic causes `ToString()` to be called on values which implement IEnumerable. This PR handles one level depth of flattening this values for showing in text loggers.
Example scenario(in case when an MVC view is not found, we would like to provide a list of locations that the view was searched for):
```c#
var viewEngineResult = viewEngine.FindView(context, viewName);
if(!viewEngineResult.Success)
{
logger.LogError(
"The view '{ViewName}' was not found. Searched locations: {SearchedViewLocations}", 
viewName,
viewEngineResult.SearchedLocations);
}
```
> Handle enumerable value when formatting log values

- README.md
Adds a link to the Serilog provider based on the original _Microsoft.Framework.Logging.Serilog_ sample.
> Add Serilog provider link

- Logging.sln
- src/Microsoft.Framework.Logging.Debug/DebugLogger.cs
- src/Microsoft.Framework.Logging.Debug/DebugLoggerFactoryExtensions.cs
- src/Microsoft.Framework.Logging.Debug/DebugLoggerProvider.cs
- src/Microsoft.Framework.Logging.Debug/Microsoft.Framework.Logging.Debug.xproj
- src/Microsoft.Framework.Logging.Debug/project.json
Fixes https://github.com/aspnet/Logging/issues/194
Please review @davidfowl @DamianEdwards @mikaelm12
> Debug logger

- src/Microsoft.Framework.Logging.Debug/DebugLogger.cs
- src/Microsoft.Framework.Logging.Debug/DebugLoggerFactoryExtensions.cs
- src/Microsoft.Framework.Logging.Debug/DebugLoggerProvider.cs
In response to the comments [here](https://github.com/aspnet/Logging/pull/207)
@DamianEdwards @davidfowl
> Doc comments for debug logger

- src/Microsoft.Framework.Logging.TraceSource/Internal/TraceSourceScope.cs
- src/Microsoft.Framework.Logging.TraceSource/TraceSourceFactoryExtensions.cs
- src/Microsoft.Framework.Logging.TraceSource/TraceSourceLogger.cs
- src/Microsoft.Framework.Logging.TraceSource/TraceSourceLoggerProvider.cs
- test/Microsoft.Framework.Logging.Test/TraceSourceScopeTest.cs
For consistency with the other loggers' namespaces.
Fixes #192
> Move TraceSourceLoggerProvider to Microsoft.Framework.Logging.TraceSource

- src/Microsoft.Framework.Logging/project.json
It was unused and prevented the package from installing on UWP projects.
@rowanmiller @natemcmaster
> Remove System.Diagnostics.TraceSource dependency

- src/Microsoft.Framework.Logging.TraceSource/TraceSourceLogger.cs
- src/Microsoft.Framework.Logging.TraceSource/TraceSourceScope.cs
- test/Microsoft.Framework.Logging.Test/TraceSourceScopeTest.cs
I understand the reasoning behind exposing some types publicly under an `*.Internal` namespace (so its available to "use at your own risk"), but I don't think `TraceSourceScope` warrants being public. It's not providing any new functionality that can't be called directly and an instance can be accessed through `ILogger.BeginScopeImpl()`.
> Make TraceSourceScope internal

- src/Microsoft.Framework.Logging/project.json
Fixes aspnet/EntityFramework#2680. See also aspnet/dnx#2031.
> Remove design-time facade reference from nupkg on net45

- test/Microsoft.Framework.Logging.Test/Console/TestConsole.cs
- test/Microsoft.Framework.Logging.Test/ConsoleLoggerTest.cs
TestConsole now has the own implementation of ResetColor() and ConsoleLoggerTest use a TestConsole instead System.Console. This fixes aspnet/Logging#235.
> Fixes issue when logging test fails if console background is not black

- src/Microsoft.Extensions.Logging/Logger.cs
* Only create logger array when loggers
* Normal for loop condition in constructor
* Log nop when no loggers
* BeginScope to return null when no loggers
* Logging is disabled when no loggers
* Add provider to only create one resized array; rather than several
> Reduce allocs when no loggers

- src/Microsoft.Extensions.Logging.Abstractions/ILoggerFactory.cs
- src/Microsoft.Extensions.Logging.Testing/NullLoggerFactory.cs
- src/Microsoft.Extensions.Logging.Testing/TestLoggerFactory.cs
- src/Microsoft.Extensions.Logging/Logger.cs
- src/Microsoft.Extensions.Logging/LoggerFactory.cs
- test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs
- test/Microsoft.Extensions.Logging.Test/TestLoggerFactory.cs
- test/Microsoft.Extensions.Logging.Testing.Tests/NullLoggerFactoryTest.cs
#298 
I will update the following repos:
- EntityFramework https://github.com/aspnet/EntityFramework/pull/3956
- KestrelHttpServer https://github.com/aspnet/KestrelHttpServer/pull/445
- SignalR-Redis https://github.com/aspnet/SignalR-Redis/pull/21
These repos are also affected but they are decoupled from our builds and most of them are updated only when we release. Also some don't seem relevant.
- EntityFramework.Benchmark
- NodeServices
- MusicStoreAngular2
- live.asp.net
- go.asp.net
- get.asp.net
- Docs
- KExpense
- PackageSearch
> Removing MinimumLevel from ILoggerFactory #298

- samples/SampleApp/Program.cs
- samples/SampleApp/logging.json
- src/Microsoft.Extensions.Logging.Abstractions/LogLevel.cs
- src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs
- src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
- src/Microsoft.Extensions.Logging.EventLog/EventLogLogger.cs
- src/Microsoft.Extensions.Logging.NLog/NLogLoggerProvider.cs
- src/Microsoft.Extensions.Logging.TraceSource/TraceSourceLogger.cs
- test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs
- test/Microsoft.Extensions.Logging.Test/LoggerExtensionsTest.cs
- test/Microsoft.Extensions.Logging.Test/TraceSourceLoggerTest.cs
- test/Microsoft.Extensions.Logging.Testing.Tests/NullLoggerTest.cs
Issue #299 
Renaming `LogLevel`s in logging so that `Verbose` is renamed to `Trace` and is considered less severe than `Debug`.
Most severe level listed first:
Current Levels  | New Levels
------------- | -------------
Critical  | Critical 
Error | Error 
Warning | Warning 
Information  | Information 
Verbose | Debug 
Debug | Trace 
I will update the affected repos:
- DataProtection https://github.com/aspnet/DataProtection/pull/112
- UserSecrets https://github.com/aspnet/UserSecrets/pull/52
- dnx-watch https://github.com/aspnet/dnx-watch/pull/39
- Hosting https://github.com/aspnet/Hosting/pull/512
- WebListener https://github.com/aspnet/WebListener/pull/157
- EntityFramework https://github.com/aspnet/EntityFramework/pull/3998
- StaticFiles https://github.com/aspnet/StaticFiles/pull/95
- …
> Renaming LogLevel.Verbose to Trace #299

- src/Microsoft.Extensions.Logging.Abstractions/project.json
- src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
- src/Microsoft.Extensions.Logging.Console/project.json
- src/Microsoft.Extensions.Logging/project.json
Should fix test failures in Entropy on Mac.
> Use a platform determiner which is available on all platforms

- src/Microsoft.Extensions.Logging.Abstractions/LogLevel.cs
- test/Microsoft.Extensions.Logging.Test/LogLevelEnumTest.cs
- test/Microsoft.Extensions.Logging.Test/LoggerTest.cs
> Revise LogLevel Enum

- src/Microsoft.Extensions.Logging.Testing/project.json
- src/Microsoft.Extensions.Logging.TraceSource/project.json
- src/Microsoft.Extensions.Logging/project.json
Without this, the packages won't install into "classic" Full .NET projects
> Don't reference design-time facades on net451

- src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
- test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs
> Set background color with foreground color in ConsoleLogger 

- src/Microsoft.Extensions.Logging/LoggingServiceCollectionExtensions.cs
- test/Microsoft.Extensions.Logging.Test/LoggingServiceCollectionExtensionsTest.cs
- test/Microsoft.Extensions.Logging.Test/project.json
Previously the AddLogging method did this. It is also common in other builder methods like this. It doesn't do any harm for those that don't want to chain and allows cleaner code with fewer variable declarations for those that do.
More details:
We often write code like this:
```C#\
var appServiceProivder = new ServiceCollection()
.AddLogging()
.AddCaching()
.BuildServiceProvider();
```
This is really clean and easy to read. When we are no longer able to chain we have to write this instead:
```C#
var serviceCollection = new ServiceCollection();
serviceCollection.AddLogging();
serviceCollection.AddCaching();
var appServiceProivder = serviceCollection.BuildServiceProvider();
```
This additional clutter detracts from the overall readability of the code.
Furthermore, the benefits of this kind …
> Return IServiceCollection from AddLogging so that additional calls can be chained

- samples/SampleApp/Program.cs
- src/Microsoft.Extensions.Logging.Abstractions/ILogger.cs
- src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs
- src/Microsoft.Extensions.Logging.Abstractions/LoggerMessage.cs
- src/Microsoft.Extensions.Logging.Abstractions/LoggerOfT.cs
- src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
- src/Microsoft.Extensions.Logging.Debug/DebugLogger.cs
- src/Microsoft.Extensions.Logging.EventLog/EventLogLogger.cs
- src/Microsoft.Extensions.Logging.Filter/Internal/FilterLogger.cs
- src/Microsoft.Extensions.Logging.Testing/NullLogger.cs
- src/Microsoft.Extensions.Logging.Testing/NullLoggerOfT.cs
- src/Microsoft.Extensions.Logging.Testing/TestLogger.cs
- src/Microsoft.Extensions.Logging.Testing/TestLoggerOfT.cs
- src/Microsoft.Extensions.Logging.TraceSource/TraceSourceLogger.cs
- src/Microsoft.Extensions.Logging/Logger.cs
- test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs
- test/Microsoft.Extensions.Logging.Test/DebugLoggerTest.cs
- test/Microsoft.Extensions.Logging.Test/EventLogLoggerTest.cs
- test/Microsoft.Extensions.Logging.Test/LoggerTest.cs
- test/Microsoft.Extensions.Logging.Test/TestLogger.cs
- test/Microsoft.Extensions.Logging.Test/TraceSourceScopeTest.cs
- test/Microsoft.Extensions.Logging.Testing.Tests/NullLoggerTest.cs
Reduces allocations when none of the registered loggers are tracking scope state. In particular when there are no loggers at all.
Closes #366
> Changing BuildScopeImpl to BuildScope<TState>

- src/Microsoft.Extensions.Logging.TraceSource/TraceSourceFactoryExtensions.cs
- test/Microsoft.Extensions.Logging.Test/TraceSourceLoggerTest.cs
We enabled passing null TraceListener but extension methods were not updated accordingly and would still not allow to pass a null TraceListner.
> Addendum to #405

- src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
- src/Microsoft.Extensions.Logging.Console/Internal/WindowsLogConsole.cs
- test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs
The code has been improved by:
- Pre-computing the state before locking
- Reducing the amount of allocations of color objects
- Reducing the amount of calls to Console.Write to the minimum, while still supporting colors.
Tests have been adjusted after the changes, and a couple new tests were added. This PR is intended to be merged into the 'dev' branch.
/cc @rynowak @sivagms @anpete @Eilon @SajayAntony @mnltejaswini @muratg @DamianEdwards @danroth27 @divega
> Reducing the amount of time ConsoleLogger locks

- src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
- src/Microsoft.Extensions.Logging.Console/project.json
Part of https://github.com/aspnet/PlatformAbstractions/issues/34
> Replace PlatformAbstractions with RuntimeInformation

- src/Microsoft.Extensions.Logging.Console/Internal/AnsiLogConsole.cs
- test/Microsoft.Extensions.Logging.Test/AnsiLogConsoleTest.cs
> Use standard ansi color codes

- src/Microsoft.Extensions.Logging.EventSource/EventSourceLogger.cs
- src/Microsoft.Extensions.Logging.EventSource/EventSourceLoggerProvider.cs
- src/Microsoft.Extensions.Logging.EventSource/LoggingEventSource.cs
- test/Microsoft.Extensions.Logging.EventSource.Test/EventSourceLoggerTest.cs
The behavior of `OnEventCommand` callback changed between `.NET 4.5.2` and `.NET 4.6`. In the latter the internal `EventSource` level has changed before calling the `OnEventCommand` callback which was behavior we relied on to set the loggers level. Because it isn't set before the callback in `.NET 4.5.2` we delay the original behavior of the callback until a time after the Event change occurs.
#328
> Fix EventLogger in .NET 4.5.2

- Logging.sln
- src/Microsoft.Extensions.Logging.Abstractions/Internal/NullLogger.cs
- src/Microsoft.Extensions.Logging.Abstractions/Internal/NullLoggerProvider.cs
- src/Microsoft.Extensions.Logging.Abstractions/Internal/NullScope.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/AzureWebAppDiagnosticsFactoryExtensions.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/AzureWebAppDiagnosticsLoggerProvider.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/Internal/BackgroundSink.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/Internal/FileLoggerProvider.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/Internal/IWebAppContext.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/Internal/IWebAppLogConfigurationReader.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/Internal/SerilogLoggerProvider.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/Internal/WebAppContext.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/Internal/WebAppLogConfiguration.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/Internal/WebAppLogConfigurationBuilder.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/Internal/WebAppLogConfigurationReader.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.xproj
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/Properties/AssemblyInfo.cs
- src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/project.json
- src/Microsoft.Extensions.Logging/Logger.cs
- test/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.Test/BackgroundSinkTests.cs
- test/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.Test/LogConfigurationReaderTests.cs
- test/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.Test/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.Test.xproj
- test/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.Test/SerilogLoggerProviderTests.cs
- test/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.Test/SettingsFileContent.cs
- test/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.Test/TestSink.cs
- test/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.Test/project.json
WIP implementation for https://github.com/aspnet/Logging/issues/466. Sending to get some early feedback. Tests are on the way.
Please review @pakrym @kichalla @davidfowl
> A logger for Azure WebApps

- README.md
We've created a new logger for elmah.io based on .NET Core.
> Switched URL to elmah.io extensions logger

- src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs
- src/Microsoft.Extensions.Logging.Abstractions/Internal/LogValuesFormatter.cs
- src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs
- src/Microsoft.Extensions.Logging.Debug/DebugLogger.cs
- test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs
- test/Microsoft.Extensions.Logging.Test/FormattedLogValuesTest.cs
Resolves https://github.com/aspnet/Logging/issues/422
cc @muratg @BrennanConroy
> Harden log formatters to handle null formats, null arguments, and null arrays of arguments

- src/Microsoft.Extensions.Logging.AzureAppServices/AzureAppServicesDiagnosticsSettings.cs
- src/Microsoft.Extensions.Logging.AzureAppServices/Internal/AzureAppServicesDiagnosticsLoggerProvider.cs
- src/Microsoft.Extensions.Logging.AzureAppServices/Internal/FileLoggerProvider.cs
- src/Microsoft.Extensions.Logging.AzureAppServices/project.json
And use it.
Closes: https://github.com/aspnet/Logging/issues/497
> Update to newer version of Serilog that supports flushing

- src/Microsoft.Extensions.Logging.EventSource/EventSourceLogger.cs
- src/Microsoft.Extensions.Logging.EventSource/EventSourceLoggerFactoryExtensions.cs
- src/Microsoft.Extensions.Logging.EventSource/EventSourceLoggerProvider.cs
- src/Microsoft.Extensions.Logging.EventSource/ExceptionInfo.cs
- src/Microsoft.Extensions.Logging.EventSource/LoggingEventSource.cs
- src/Microsoft.Extensions.Logging.EventSource/Properties/AssemblyInfo.cs
- test/Microsoft.Extensions.Logging.EventSource.Test/EventSourceLoggerTest.cs
- test/Microsoft.Extensions.Logging.EventSource.Test/project.json
1. Change namespace to be the same as project name.
2. Make LoggingEventSource internal.
3. Minor code style fixes.
@pranavkm
> Cleanup EventSource logging provider

- src/Microsoft.Extensions.Logging.AzureAppServices/AzureAppServicesDiagnosticsSettings.cs
- src/Microsoft.Extensions.Logging.AzureAppServices/Internal/AzureBlobSink.cs
- src/Microsoft.Extensions.Logging.AzureAppServices/Internal/FileLoggerProvider.cs
- src/Microsoft.Extensions.Logging.AzureAppServices/project.json
Fixes: https://github.com/aspnet/Logging/issues/508 https://github.com/aspnet/Logging/issues/506 https://github.com/aspnet/Logging/issues/507
> Fix comments, typos and add property validation to Microsoft.Extensions.Logging.AzureAppServices

- src/Microsoft.Extensions.Logging.AzureAppServices/AzureAppServicesDiagnosticsSettings.cs
> Fix more comments and property validation in Microsoft.Extensions.Logging.AzureAppServices

- test/Microsoft.Extensions.Logging.AzureAppServices.Test/Microsoft.Extensions.Logging.AzureAppServices.Test.csproj
- test/Microsoft.Extensions.Logging.EventSource.Test/Microsoft.Extensions.Logging.EventSource.Test.csproj
- test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs
- test/Microsoft.Extensions.Logging.Test/EventLogLoggerTest.cs
- test/Microsoft.Extensions.Logging.Test/Microsoft.Extensions.Logging.Test.csproj
- test/Microsoft.Extensions.Logging.Test/TraceSourceLoggerProviderTest.cs
- test/Microsoft.Extensions.Logging.Test/TraceSourceLoggerTest.cs
- test/Microsoft.Extensions.Logging.Test/TraceSourceScopeTest.cs
- test/Microsoft.Extensions.Logging.Testing.Tests/Microsoft.Extensions.Logging.Testing.Tests.csproj
- aspnet/Testing#248
- xUnit no longer supports .NET 4.5.1
- build tests for desktop .NET only on Windows
> Bump test projects up to .NET 4.5.2

- src/Microsoft.Extensions.Logging.Abstractions/NullLoggerFactory.cs
Issue - #566 
Removing `NullLogger*` types from Logging.Testing will break other repos. That should be done separately.
@Eilon @muratg
> Added NullLoggerFactory to Logging.Abstractions

- src/Microsoft.Extensions.Logging.Abstractions/NullLoggerOfT.cs
Missed this type when I addressed #566 
@Eilon
> Added NullLoggerOfT to Logging.Abstractions

- src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs
- src/Microsoft.Extensions.Logging.Abstractions/Properties/AssemblyInfo.cs
- test/Microsoft.Extensions.Logging.Test/FormattedLogValuesTest.cs
#516 
@glennc @davidfowl 
I tried a ConcurrentLru cache in the initial commit, but it looked like perf halved in that scenario.
Current thought is to just cap the cache to prevent memory leaks, and if perf is a concern then the `LoggerMessage.DefineScope` pattern can be used.
Will file an issue in docs to document that pattern: https://github.com/aspnet/Docs/issues/2810
> Cap FormattedLogValues cache

- src/Microsoft.Extensions.Logging.Testing/Microsoft.Extensions.Logging.Testing.csproj
@Eilon FYI if we have plans to ship this on NuGet, we'll need a follow-up issue to create baselines and revert this change after that release.
> Disable API Check for package that we do not push to NuGet

- src/Microsoft.Extensions.Logging.Console/Internal/ConsoleLoggerProcessor.cs
- test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs
- Check complete adding before adding new messages
to the list.
- Added a test
#563
PS: I didn't measure the performance of checking that bool on every write.
> Logging shouldn't throw after dispose

- src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs
- test/Microsoft.Extensions.Logging.Test/LoggerExtensionsTest.cs
This PR adds the following extension method: 
`Log....(this ILogger logger, Exception exception, string message, params object[] args);`
This has been requested in #350 and #294.
I think this would be a great addition for two reasons:
- There already are other extension methods without EventId - having this method makes it more consistent
- This makes EventIds completely optional for people who don't want to use them
> Extension methods for Log*(exception, message, args)

- Logging.sln
- build/dependencies.props
- src/Microsoft.Extensions.Logging.Testing/AssemblyTestLog.cs
- src/Microsoft.Extensions.Logging.Testing/LoggedTest.cs
- src/Microsoft.Extensions.Logging.Testing/Microsoft.Extensions.Logging.Testing.csproj
- test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs
- test/Microsoft.Extensions.Logging.Testing.Tests/TestTestOutputHelper.cs
- test/Microsoft.Extensions.Logging.Testing.Tests/XunitLoggerProviderTest.cs
@davidfowl really wanted this available as low as possible, so I've moved it from IntegrationTesting to here, Logging.Testing. This is a noship package already.
@Eilon The Serilog dependency is moving once again, from Hosting to here. Once this is merged, I'll be converting the IntegrationTesting package to use it and removing the dependency there.
I also restructured this to allow me to write some tests for it.
> copy test logging stuff from IntegrationTesting here

- test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs
Going to merge when I get green builds. This is causing flakiness in the CI because if the tests finish fast enough, the duration doesn't match the regex.
> make the regex for testing more consistent

- samples/SampleApp/Program.cs
- samples/SampleApp/SampleApp.csproj
This PR removes all references to PlatformAbstractions.
Part of aspnet/PlatformAbstractions#50
> react to removal of PlatformAbstractions

- build/dependencies.props
- test/Microsoft.Extensions.Logging.AzureAppServices.Test/AzureBlobSinkTests.cs
- test/Microsoft.Extensions.Logging.AzureAppServices.Test/Microsoft.Extensions.Logging.AzureAppServices.Test.csproj
- test/Microsoft.Extensions.Logging.EventSource.Test/Microsoft.Extensions.Logging.EventSource.Test.csproj
- test/Microsoft.Extensions.Logging.Test/LoggerExtensionsTest.cs
- test/Microsoft.Extensions.Logging.Test/Microsoft.Extensions.Logging.Test.csproj
- test/Microsoft.Extensions.Logging.Testing.Tests/Microsoft.Extensions.Logging.Testing.Tests.csproj
Upgrade to xunit2.3 and test SDK 15.3.
:watch: blocked on https://github.com/aspnet/KestrelHttpServer/pull/1834 which has a down-stream dependency on Logging.Testing. This can't merge until Kestrel has also updated to xunit 2.3.
> Upgrade test framework versions and fix test issues

- src/Microsoft.Extensions.Logging/LoggerRuleSelector.cs
- test/Microsoft.Extensions.Logging.Test/ProviderAliasAttribute.cs
- test/Microsoft.Extensions.Logging.Test/TestLoggerProvider.cs
ApplicationInsights in particular
> Late bind ProviderAlias attribute to support libraries unable to reference new logging package

- src/Microsoft.Extensions.Logging.Console/Internal/ConsoleLoggerProcessor.cs
I see no need for the indirection to the static method, which in turn only calls the instance method.
```c#
public ConsoleLoggerProcessor()
{
// Start Console message queue processor
_outputTask = Task.Factory.StartNew(
ProcessLogQueue,
this,
TaskCreationOptions.LongRunning);
}
private void ProcessLogQueue()
{
foreach (var message in _messageQueue.GetConsumingEnumerable())
{
WriteMessage(message);
}
}
private static void ProcessLogQueue(object state)
{
var consoleLogger = (ConsoleLoggerProcessor)state;
consoleLogger.ProcessLogQueue();
}
```
The (little) change uses the instance method directly in the `Task.Factory.StartNew` method.
> Removed indirection in starting the consumer in ConsoleLoggerProcessor

- src/Microsoft.Extensions.Logging.Abstractions/Internal/LogValuesFormatter.cs
- test/Microsoft.Extensions.Logging.Test/FormattedLogValuesTest.cs
Fixes #656
Fix issue parsing log message format strings with placeholders containing a format string with a comma ",", such as "{setupTime:#,#}" which uses a custom numeric format string with a group separator. This fix uses the index of the first first comma "," or colon ":" found as the delimiter instead of ignoring the colon ":" if a comma "," was found.
> Fix #656 - issue parsing format string w/ group separator

- src/Microsoft.Extensions.Logging.AzureAppServices/AzureAppServicesLoggerFactoryExtensions.cs
- src/Microsoft.Extensions.Logging.Console/ConsoleLoggerFactoryExtensions.cs
- src/Microsoft.Extensions.Logging.Debug/DebugLoggerFactoryExtensions.cs
- src/Microsoft.Extensions.Logging.EventLog/EventLoggerFactoryExtensions.cs
- src/Microsoft.Extensions.Logging.EventSource/EventSourceLoggerFactoryExtensions.cs
- src/Microsoft.Extensions.Logging.Testing/XunitLoggerFactoryExtensions.cs
- test/Microsoft.Extensions.Logging.Analyzer.Test/DiagnosticVerifier.cs
- test/Microsoft.Extensions.Logging.AzureAppServices.Test/LoggerBuilderExtensionsTests.cs
- test/Microsoft.Extensions.Logging.AzureAppServices.Test/Microsoft.Extensions.Logging.AzureAppServices.Test.csproj
- test/Microsoft.Extensions.Logging.EventSource.Test/AzureAppServicesLoggerFactoryExtensionsTests.cs
- test/Microsoft.Extensions.Logging.Test/LoggerBuilderExtensionsTests.cs
Fixes: https://github.com/aspnet/MetaPackages/issues/162
To prevent duplicated logs if people call `builder.Add*` multiple times
> Use TryAddEnumerable to prevernt adding logger provider multiple times

- test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs
Noticed this when I ran Universe locally. These tests were failing because of how the *.cs file was checked out, which shouldn't happen.
> Make tests newline agnostic

- src/Microsoft.Extensions.Logging.Testing/AssemblyTestLog.cs
- src/Microsoft.Extensions.Logging.Testing/LoggedTest.cs
- test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs
Also, the tests were leaving directories and files around in Temp. That ended up requiring some changes to how objects are disposed because they were keeping the test files locked.
> [Logging.Testing] Drop test logging level down to Trace

- src/Microsoft.Extensions.Logging.Testing/AssemblyTestLog.cs
- test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs
`NET Core 4.6.26020.03` for 2.0
`NET Core 4.6.26130.05` for 2.1
`NET Framework 4.7.2117.0` for Full Framework
> Split test log out directory by framework the test ran under

- test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs
`Directory.Delete` sometimes doesn't delete things the first time. Make it retry after a delay to allow file system handles to get free.
Fixes: https://github.com/aspnet/Logging/issues/745
> Add logic to retry folder deletion

- src/Microsoft.Extensions.Logging.Testing/XunitLoggerProvider.cs
If logging an empty string, e.g. "", this fails to get lines.First().
This fix worked for my copy of this code.
> Update for when log message is an empty string

- src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs
Changes the `<example>` tags for LogDebug and LogCritical to match the signature of the overload.
> Fix documentation errors for log extension methods

- build/dependencies.props
- korebuild-lock.txt
- test/Microsoft.Extensions.Logging.Test/ConsoleLoggerTest.cs
- test/Microsoft.Extensions.Logging.Test/TraceSourceLoggerProviderTest.cs
Recent logging failures were caused by tests logging to TraceSource so I fixed that.
While investigating failures I thought it was caused by an error being logged to console so redirected console output too.
> Harden logging tests

- src/Microsoft.Extensions.Logging.AzureAppServices/AzureAppServicesLoggerFactoryExtensions.cs
- test/Microsoft.Extensions.Logging.AzureAppServices.Test/LoggerBuilderExtensionsTests.cs
https://github.com/aspnet/AzureIntegration/issues/177
It was regressed by https://github.com/aspnet/Logging/pull/719, `loggerBuilder.AddConfiguration` adds some services that we call `TryAddEnumerable` on afterwards. It causes us not to add required configuration change token source.
> Add azure logging change token source unconditionally

- src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs
- test/Microsoft.Extensions.Logging.Test/LoggerExtensionsTest.cs
This PR expands on #629.  Changes:
* Adds a new extension method that also accepts an `EventId` and an `Exception`
* Update [the previous method](https://github.com/ChrisSimmons/Logging/blob/a4b901159255abbdd47cf979171838799f971f66/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L350) to use this new method
* Update all the level-specific methods (e.g. [`LogDebug()`](https://github.com/ChrisSimmons/Logging/blob/a4b901159255abbdd47cf979171838799f971f66/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L42) and [`LogWarning()`](https://github.com/ChrisSimmons/Logging/blob/a4b901159255abbdd47cf979171838799f971f66/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L191)) to use this new method
* Use the new method to [handle the null `logger` …
> Expand log level extension

- build/dependencies.props
- src/Microsoft.Extensions.Logging.Testing/Xunit/LoggedTestInvoker.cs
- test/Microsoft.Extensions.Logging.Testing.Tests/LoggedTestXunitTests.cs
Addresses #819. Though this is a good thing to fix, I don't think this is causing the exception you are seeing. 
The exceptions that might occur are caught here: https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Testing/XunitLoggerProvider.cs#L90-L100. This explains why our tests were working and were writing to file. However, I'm no longer sure why debugging is broken on your machine.
> Initialize ITestOutputHelper earlier

- src/Microsoft.Extensions.Logging.Testing/AssemblyTestLog.cs
- src/Microsoft.Extensions.Logging.Testing/LoggedTest/ILoggedTest.cs
- src/Microsoft.Extensions.Logging.Testing/LoggedTest/LoggedTestBase.cs
- src/Microsoft.Extensions.Logging.Testing/TestFrameworkFileLoggerAttribute.cs
- src/Microsoft.Extensions.Logging.Testing/build/Microsoft.Extensions.Logging.Testing.props
- test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs
Old Path: Logging\artifacts\logs\Microsoft.Extensions.Logging.Testing.Tests\NET Framework 4.7.2650.0\AssemblyTestLogTests\ForAssembly_ReturnsSameInstanceForSameAssembly.log
New Path: Logging\artifacts\logs\Microsoft.Extensions.Logging.Testing.Tests\net461\AssemblyTestLogTests\ForAssembly_ReturnsSameInstanceForSameAssembly.log
> Change the file logger directory to use tfm

- src/Microsoft.Extensions.Logging.Testing/AssemblyTestLog.cs
- src/Microsoft.Extensions.Logging.Testing/TestFrameworkFileLoggerAttribute.cs
- src/Microsoft.Extensions.Logging.Testing/build/Microsoft.Extensions.Logging.Testing.props
- test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs
Couldn't find a way to ensure references to Logging.Testing are marked with PrivateAssets="None" so I'm opting to add a more explicit error instead. Also adding an environment variable to turn off file logging which is now on by default and there's no way of turning it off.
> Add opt-out for file logging and add error when FileLoggerAttribute is missing

- src/Microsoft.Extensions.Logging/LoggerFactory.cs
Resolves https://github.com/aspnet/Logging/issues/810
CreateLogger -> CreateLoggers is under lock https://github.com/aspnet/Logging/blob/073a98266684d9c643a02ac3f0f30712a35a9914/src/Microsoft.Extensions.Logging/LoggerFactory.cs#L70-L82
However... `AddProviderRegistration` in `AddProvider` isn't https://github.com/aspnet/Logging/blob/073a98266684d9c643a02ac3f0f30712a35a9914/src/Microsoft.Extensions.Logging/LoggerFactory.cs#L85-L94
Which will change the size of the `_providerRegistrations` List and cause `Index was outside the bounds of the array.` error as `_loggers` doesn't change size.
/cc @JamesNK @pakrym @davidfowl 
@muratg should this be 2.1?
> Move AddProviderRegistration under lock

- src/Microsoft.Extensions.Logging.Abstractions/EventId.cs
- src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
Add readonly to `EventId` and `ConsoleColors` structures.
> Add readonly to EventId and ConsoleColors structures

- src/Microsoft.Extensions.Logging.Testing/AssemblyTestLog.cs
- src/Microsoft.Extensions.Logging.Testing/Xunit/LoggedTestInvoker.cs
- src/Microsoft.Extensions.Logging.Testing/Xunit/LoggedTestRunner.cs
- src/Microsoft.Extensions.Logging.Testing/XunitLoggerFactoryExtensions.cs
- src/Microsoft.Extensions.Logging.Testing/XunitLoggerProvider.cs
- test/Microsoft.Extensions.Logging.Testing.Tests/AssemblyTestLogTests.cs
- Standardize timestamp to use offsets in xunit output.
- Return the TestOutputHelper's output back to xunit so it doesn't go to /dev/null.
> Timestamp and ITestOutputHelper fixes

- README.md
Sharpbrake is a C# notifier library for [Airbrake](https://airbrake.io/) - an online tool that provides error tracking for applications. The [Sharpbrake.Extensions.Logging](https://www.nuget.org/packages/Sharpbrake.Extensions.Logging) provider notifies the Airbrake dashboard of an error with the help of the Microsoft.Extensions.Logging API.
> Add Sharpbrake to the list of community projects

- src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs
Remove [redundant `if` condition](https://github.com/aspnet/Logging/blob/bdd33cdcfd6345c01f820ae0726c49b2c3bc4939/src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs#L171) that checks for the `StringBuilder` being empty, when it always contains [at least 6 characters](https://github.com/aspnet/Logging/blob/bdd33cdcfd6345c01f820ae0726c49b2c3bc4939/src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs#L143-L147) (`':'`, `' '`, `'['`, `'{digit}'`, `']'`, `'\n'`).
> Remove redundant if condition from ConsoleLogger

- src/Microsoft.Extensions.Logging.Testing/LoggedTest/LoggedTestBase.cs
- src/Microsoft.Extensions.Logging.Testing/RetryContext.cs
- src/Microsoft.Extensions.Logging.Testing/Xunit/LoggedTestInvoker.cs
- src/Microsoft.Extensions.Logging.Testing/Xunit/LoggedTestRunner.cs
- src/Microsoft.Extensions.Logging.Testing/Xunit/RetryTestAttribute.cs
- test/Microsoft.Extensions.Logging.Testing.Tests/LoggedTestXunitRetryTests.cs
I'm piggy-backing off the infrastructure we have in place for LoggedTest since that is much simpler than creating its own set of discoverers, runners and invokers. It would also make it hard to handle a test class that's both logged and retried. The trade-off is that all retried tests must also be logged and I think that's reasonable since most of the tests would be functional tests that should be logged anyway.
Backgound:
We have some functional tests in Kestrel that's flaky on macOS due to underlying issues in the kernel. We don't want to disable all affected tests since that would dramatically reduce our coverage. In these cases, we would want to retry tests. This should only be allowed on tests with well known diagnosis and when all other possible fixes has been implemented.
This will …
> Add retry capability to tests

- src/Microsoft.Extensions.Logging.EventSource/LoggingEventSource.cs
- test/Microsoft.Extensions.Logging.EventSource.Test/EventSourceLoggerTest.cs
Found some issues with the logger when doing E2E testing with perfview.
> Fix EventSource logger for cases where listener exists before app starts

- src/Microsoft.Extensions.Logging.AzureAppServices/AzureBlobLoggerOptions.cs
- src/Microsoft.Extensions.Logging.AzureAppServices/Internal/BatchingLoggerOptions.cs
Fixes: https://github.com/aspnet/Logging/issues/821
We had it backwards with limited batch size and unlimited queue.
Queue size is now 1000 and batch size is unlimited to unload logs as fast as possible.
> Change azure logger defaults

- src/Microsoft.Extensions.Logging.AzureAppServices/AzureFileLoggerOptions.cs
The property FileName was the same as the one for `RetainedFileCountLimit`, this commits changes to something that describes this property more correctly.
Fixes #863
> Fixes the description for the property FileName

- src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs
Fixes: https://github.com/aspnet/Logging/issues/824
We have existing tests for passing null to FormattedLogValues:
https://github.com/aspnet/Logging/blob/master/test/Microsoft.Extensions.Logging.Test/FormattedLogValuesTest.cs
> Fix lazy formatter creation condition

- .gitignore
- Logging.sln
- benchmarks/Logging.Performance/LogValuesBenchmarks.cs
- benchmarks/Logging.Performance/Logging.Performance.csproj
- benchmarks/Logging.Performance/LoggingBenchmarkBase.cs
- benchmarks/Logging.Performance/LoggingOverheadBenchmark.cs
- benchmarks/Logging.Performance/ScopesOverheadBenchmark.cs
- build/dependencies.props
- src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs
- src/Microsoft.Extensions.Logging.Abstractions/Internal/LogValuesFormatter.cs
- src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs
- src/Microsoft.Extensions.Logging.Abstractions/LoggerMessage.cs
1. Make a lot of things struct to avoid boxing
2. Add specialized overloads for 1-3 parameter messages that match `string.Format` and avoid allocation
3. Fix some special casing for no argument logs
```
Method |      Mean |     Error |    StdDev |         Op/s | Scaled | ScaledSD |  Gen 0 | Allocated |
------------------------------------------- |----------:|----------:|----------:|-------------:|-------:|---------:|-------:|----------:|
NoArguments_FilteredByLevel |  54.30 ns | 0.4572 ns | 0.4053 ns | 18,415,469.9 |   2.72 |     0.02 | 0.0001 |      40 B |
NoArguments_DefineMessage_FilteredByLevel |  19.94 ns | 0.1230 ns | 0.1027 ns | 50,138,751.2 |   1.00 |     0.00 |      - |       0 B |
NoArguments |  74.18 ns | 1.2185 ns | 1.1398 ns | 13,480,512.4 |   3.72 |     0.06 | 0.0001 | …
```
> Decrease logging overhead

- benchmarks/Logging.Performance/ScopesOverheadBenchmark.cs
- src/Microsoft.Extensions.Logging.Configuration/LoggerFilterConfigureOptions.cs
- src/Microsoft.Extensions.Logging/Logger.cs
- src/Microsoft.Extensions.Logging/LoggerFactory.cs
- src/Microsoft.Extensions.Logging/LoggerFilterOptions.cs
- test/Microsoft.Extensions.Logging.Test/LoggerFilterTest.cs
- test/Microsoft.Extensions.Logging.Test/LoggerTest.cs
- test/Microsoft.Extensions.Logging.Test/TestConfiguration.cs
https://github.com/aspnet/Logging/issues/714
https://github.com/aspnet/Logging/issues/875
After adding a common infrastructure for capturing scopes (IExternalScopeProvider) it became impossible for providers to control if scopes are being captured.
Most prominent example of this is console logger that became slower in common case event when `IncludeScopes` is set to false.
This change adds `CaptureScopes` flag that disables capturing scopes for all loggers. There is no point to add a flag per provider because our goal is to use `IExternalScopeProvider` in all of them to avoid the overhead and disabling single provider wouldn't have any effect until all that use `IExternalScopeProvider` are disabled.
With `CaptureScopes == false` performance is the same as using logger provider that …
> Add an ability to disable scope capturing

- build/dependencies.props
- build/sources.props
- src/Microsoft.Extensions.Logging.Analyzers/Microsoft.Extensions.Logging.Analyzers.csproj
- test/Microsoft.Extensions.Logging.Analyzer.Test/Microsoft.Extensions.Logging.Analyzer.Test.csproj
This was failing to auto-update because of the PrivateAssets and the
conflicts with the shared framework which has 2.8.0 inside.
> Update Roslyn version

- src/Microsoft.Extensions.Logging/LoggerRuleSelector.cs
- test/Microsoft.Extensions.Logging.Test/LoggerFilterTest.cs
Only a single wildcard character is supported per category name.
Fixes: https://github.com/aspnet/Logging/issues/779
> Add support for category wildcards

- src/Microsoft.Extensions.Logging.Console/Internal/WindowsLogConsole.cs
Calling ResetColor is as expensive as writing messages:
Before:
After:
> Avoid calling ResetColor when colors are disabled

- src/Microsoft.Extensions.Logging/Logger.cs
- src/Microsoft.Extensions.Logging/LoggerFactory.cs
- src/Microsoft.Extensions.Logging/LoggerInformation.cs
- test/Microsoft.Extensions.Logging.Test/LoggerFactoryTest.cs
By unloading more logic from the hot path to logger creation time.
Fixes: https://github.com/aspnet/Logging/issues/894
Fixes: https://github.com/aspnet/Logging/issues/714
Also `LoggerFactory` is much more readable now.
Before:
```
Method | CaptureScopes |     Mean |    Error |   StdDev |        Op/s |  Gen 0 | Allocated |
--------------------- |-------------- |---------:|---------:|---------:|------------:|-------:|----------:|
MultipleMixedLoggers |         False | 185.4 ns | 1.233 ns | 1.093 ns | 5,393,087.5 |      - |       0 B |
MultipleMixedLoggers |          True | 310.3 ns | 3.418 ns | 2.854 ns | 3,222,362.8 | 0.0005 |     168 B |
```
After:
```
Method | CaptureScopes |     Mean |    Error |   StdDev |        Op/s |  Gen 0 | Allocated |
--------------------- |-------------- …
```
> Optimize BeginScope performance
